### ISSUE TITLE
Failing To Download.

### ISSUE THREAD

**Issue by CantBeKarma** [TygodeVries/SimpleResoucepack#1]
Getting the following error in console while trying to download resourcepacks. Can't seem to get this working at all atm. Not sure if it's an erorr on my part or not but:

[16:09:39 ERROR]: When using the applyResoucepack() method, you should add the .zip at the end of the name.

Using Pufferfish Build #46.
Using version 2.2 (https://www.spigotmc.org/resources/simple-resourcepack.113476/)

**Comment by TygodeVries** [comment]
Hey Karma,

Thanks for your report!
I added some more detailed logs into the newest version of the plugin.
Could you update the plugin to the latest version and send the error message here?

Thanks,
Tygo (TheSheepDev)

**Comment by CantBeKarma** [comment]
I've went ahead and updated, however I'm only getting:

"We were unable to download the resourcepack." and 1 out of 1 packs failed to download (referring to the default that was added).

I'm not actually getting any output in the console about why it'd be failing or anything at all unfortunately.

**Comment by TygodeVries** [comment]
I could think of the following things you can try / check

- Make sure your ip and port is setup correctly in the config
- Make sure the port is open to outside connections
- Make sure the resourcepack is set up correctly

Feel free to join the Discord, It can make trouble shooting a bit easier.

**Comment by CantBeKarma** [comment]
It was the port I was using, didn't properly open. Thanks!
