### ISSUE TITLE
Wiki Typo / Permission Bug In Game.

### ISSUE THREAD

**Issue by CantBeKarma** [TygodeVries/SimpleResoucepack#2]
In the Wiki: https://github.com/TygodeVries/SimpleResourcepack/wiki/Commands every 'permission' displayed such as "simpleresoucepack.enable.self" is a typo, since "simpleresoucepack" is missing an "r" in resource. Which, evidently leads to another typo altogether since simpleresourcepack.enable.self isn't the correct permission it seems. It's suppose to be 'simpleresourcepack.add.self' and 'simpleresourcepack.add.other'

The commands **/simpleresourcepack disable** and **/simpleresourcepack enable** used on other players are bugged. They're checking the target player for permission to use the command and even sending the error message when the target player doesn't have permission to them too.

**Comment by TygodeVries** [comment]
Thank you for taking the time to create an issue,

I edited the wiki page to fix the major typos for now.
The permission fix is now on github but spigot still needs to be updated.
